const ExcelExporter=require('./classes/ExcelExporter');
let excelExporter=new ExcelExporter();
excelExporter.rosterMonth=1;
excelExporter.rosterYear=2021;
excelExporter.vacantShiftList={
    "0": "",
    "1": "",
    "2": "",
    "3": "",
    "4": "a",
    "5": "",
    "6": "",
    "7": "",
    "8": "",
    "9": "",
    "10": "",
    "11": "",
    "12": "",
    "13": "",
    "14": "",
    "15": "",
    "16": "",
    "17": "a",
    "18": "",
    "19": "",
    "20": "",
    "21": "",
    "22": "",
    "23": "",
    "24": "a",
    "25": "",
    "26": "",
    "27": ""
}
excelExporter.rosterList={
    "ITO1_1999-01-01": {
        "lastMonthBalance": 5.7,
        "thisMonthBalance": 5.5499999999999945,
        "workingHourPerDay": 7.8,
        "shiftList": {
            "1": "b",
            "2": "O",
            "3": "a",
            "4": "a",
            "5": "O",
            "6": "c",
            "7": "c",
            "8": "O",
            "9": "a",
            "10": "O",
            "11": "b",
            "12": "d1",
            "13": "d1",
            "14": "c",
            "15": "O",
            "16": "O",
            "17": "a",
            "18": "O",
            "19": "O",
            "20": "b",
            "21": "b",
            "22": "c",
            "23": "O",
            "24": "O",
            "25": "b",
            "26": "b",
            "27": "c",
            "28": "O"
        },
        "availableShiftList": [
            "a",
            "b",
            "c",
            "d1",
            "O",
            "d2"
        ],
        "itoName": "TSANG Ka Shing Gary",
        "itoPostName": "ITO1",
        "actualWorkingHour": 140.25,
        "totalHour": 140.4,
        "thisMonthHourTotal": -0.15000000000000568,
        "shiftCountList": {
            "aShiftCount": 4,
            "bxShiftCount": 6,
            "cShiftCount": 5,
            "dxShiftCount": 2
        },
        "actualNoOfWorkingDay": 17
    },
    "ITO3_2017-10-18": {
        "lastMonthBalance": -0.3,
        "thisMonthBalance": 8.7,
        "workingHourPerDay": 9,
        "shiftList": {
            "1": "a",
            "2": "c",
            "3": "c",
            "4": "O",
            "5": "O",
            "6": "O",
            "7": "a",
            "8": "b1",
            "9": "b1",
            "10": "c",
            "11": "O",
            "12": "c",
            "13": "c",
            "14": "O",
            "15": "b1",
            "16": "b1",
            "17": "b1",
            "18": "c",
            "19": "O",
            "20": "a",
            "21": "a",
            "22": "O",
            "23": "a",
            "24": "b1",
            "25": "O",
            "26": "a",
            "27": "O",
            "28": "a"
        },
        "availableShiftList": [
            "a",
            "b1",
            "c",
            "d",
            "O"
        ],
        "itoName": "YUNG Kin Shing Tommy",
        "itoPostName": "ITO3",
        "actualWorkingHour": 171,
        "totalHour": 162,
        "thisMonthHourTotal": 9,
        "shiftCountList": {
            "aShiftCount": 7,
            "bxShiftCount": 6,
            "cShiftCount": 6,
            "dxShiftCount": 0
        },
        "actualNoOfWorkingDay": 19
    },
    "ITO4_1999-01-01": {
        "lastMonthBalance": -5.55,
        "thisMonthBalance": 9.299999999999994,
        "workingHourPerDay": 7.8,
        "shiftList": {
            "1": "c",
            "2": "O",
            "3": "b",
            "4": "c",
            "5": "O",
            "6": "a",
            "7": "d1",
            "8": "O",
            "9": "O",
            "10": "b",
            "11": "a",
            "12": "a",
            "13": "O",
            "14": "a",
            "15": "a",
            "16": "c",
            "17": "O",
            "18": "b",
            "19": "b",
            "20": "O",
            "21": "c",
            "22": "O",
            "23": "b",
            "24": "c",
            "25": "O",
            "26": "O",
            "27": "a",
            "28": "c"
        },
        "availableShiftList": [
            "a",
            "b",
            "c",
            "d1",
            "O",
            "d2"
        ],
        "itoName": "HUEN Kwai-leung Andrew",
        "itoPostName": "ITO4",
        "actualWorkingHour": 155.25,
        "totalHour": 140.4,
        "thisMonthHourTotal": 14.849999999999994,
        "shiftCountList": {
            "aShiftCount": 6,
            "bxShiftCount": 5,
            "cShiftCount": 6,
            "dxShiftCount": 1
        },
        "actualNoOfWorkingDay": 18
    },
    "ITO6_1999-01-01": {
        "lastMonthBalance": -1.67,
        "thisMonthBalance": 1.4299999999999944,
        "workingHourPerDay": 7.8,
        "shiftList": {
            "1": "d1",
            "2": "b",
            "3": "O",
            "4": "b",
            "5": "c",
            "6": "O",
            "7": "O",
            "8": "a",
            "9": "O",
            "10": "a",
            "11": "d1",
            "12": "b",
            "13": "b",
            "14": "b",
            "15": "O",
            "16": "a",
            "17": "c",
            "18": "O",
            "19": "c",
            "20": "O",
            "21": "O",
            "22": "a",
            "23": "O",
            "24": "a",
            "25": "c",
            "26": "c",
            "27": "O",
            "28": "O"
        },
        "availableShiftList": [
            "a",
            "b",
            "c",
            "d1",
            "O",
            "d2"
        ],
        "itoName": "LI Chi-wai Joseph",
        "itoPostName": "ITO6",
        "actualWorkingHour": 143.5,
        "totalHour": 140.4,
        "thisMonthHourTotal": 3.0999999999999943,
        "shiftCountList": {
            "aShiftCount": 5,
            "bxShiftCount": 5,
            "cShiftCount": 5,
            "dxShiftCount": 2
        },
        "actualNoOfWorkingDay": 17
    },
    "ITO8_1999-01-01": {
        "lastMonthBalance": 2.95,
        "thisMonthBalance": 4.5499999999999945,
        "workingHourPerDay": 7.8,
        "shiftList": {
            "1": "O",
            "2": "a",
            "3": "O",
            "4": "O",
            "5": "b",
            "6": "b",
            "7": "b",
            "8": "c",
            "9": "c",
            "10": "O",
            "11": "c",
            "12": "O",
            "13": "a",
            "14": "O",
            "15": "c",
            "16": "O",
            "17": "O",
            "18": "O",
            "19": "a",
            "20": "c",
            "21": "O",
            "22": "b",
            "23": "c",
            "24": "d1",
            "25": "d1",
            "26": "O",
            "27": "b",
            "28": "b"
        },
        "availableShiftList": [
            "a",
            "b",
            "c",
            "d1",
            "O",
            "d2"
        ],
        "itoName": "CHAN Tai-hin Jimmy",
        "itoPostName": "ITO8",
        "actualWorkingHour": 142,
        "totalHour": 140.4,
        "thisMonthHourTotal": 1.5999999999999943,
        "shiftCountList": {
            "aShiftCount": 3,
            "bxShiftCount": 6,
            "cShiftCount": 6,
            "dxShiftCount": 2
        },
        "actualNoOfWorkingDay": 17
    }
}
excelExporter.monthlyCalendar={
    "calendarDateList": [
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 1,
            "dayOfWeek": 1,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 20,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "己丑",
            "chineseDayName": "庚辰"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 2,
            "dayOfWeek": 2,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 21,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "己丑",
            "chineseDayName": "辛巳"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 3,
            "dayOfWeek": 3,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 22,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "庚寅",
            "chineseDayName": "壬午",
            "solarTermInfo": "立春"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 4,
            "dayOfWeek": 4,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 23,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "庚寅",
            "chineseDayName": "癸未"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 5,
            "dayOfWeek": 5,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 24,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "庚寅",
            "chineseDayName": "甲申"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 6,
            "dayOfWeek": 6,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 25,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "庚寅",
            "chineseDayName": "乙酉"
        },
        {
            "publicHoliday": true,
            "today": false,
            "dateOfMonth": 7,
            "dayOfWeek": 0,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 26,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "庚寅",
            "chineseDayName": "丙戌"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 8,
            "dayOfWeek": 1,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 27,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "庚寅",
            "chineseDayName": "丁亥"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 9,
            "dayOfWeek": 2,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 28,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "庚寅",
            "chineseDayName": "戊子"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 10,
            "dayOfWeek": 3,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 29,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "庚寅",
            "chineseDayName": "己丑"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 11,
            "dayOfWeek": 4,
            "animalOfYear": "鼠",
            "month": 1,
            "year": 2021,
            "lunarDate": 30,
            "lunarMonth": 12,
            "lunarYear": 2020,
            "isLeap": false,
            "chineseYearName": "庚子",
            "chineseMonthName": "庚寅",
            "chineseDayName": "庚寅"
        },
        {
            "publicHoliday": true,
            "today": false,
            "dateOfMonth": 12,
            "dayOfWeek": 5,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 1,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "辛卯",
            "festivalInfo": "大年初一"
        },
        {
            "publicHoliday": true,
            "today": false,
            "dateOfMonth": 13,
            "dayOfWeek": 6,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 2,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "壬辰",
            "festivalInfo": "年初二"
        },
        {
            "publicHoliday": true,
            "today": false,
            "dateOfMonth": 14,
            "dayOfWeek": 0,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 3,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "癸巳"
        },
        {
            "publicHoliday": true,
            "today": false,
            "dateOfMonth": 15,
            "dayOfWeek": 1,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 4,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "甲午",
            "festivalInfo": "年初三補假"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 16,
            "dayOfWeek": 2,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 5,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "乙未"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 17,
            "dayOfWeek": 3,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 6,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "丙申"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 18,
            "dayOfWeek": 4,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 7,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "丁酉",
            "solarTermInfo": "雨水"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 19,
            "dayOfWeek": 5,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 8,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "戊戌"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 20,
            "dayOfWeek": 6,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 9,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "己亥"
        },
        {
            "publicHoliday": true,
            "today": false,
            "dateOfMonth": 21,
            "dayOfWeek": 0,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 10,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "庚子"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 22,
            "dayOfWeek": 1,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 11,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "辛丑"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 23,
            "dayOfWeek": 2,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 12,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "壬寅"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 24,
            "dayOfWeek": 3,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 13,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "癸卯"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 25,
            "dayOfWeek": 4,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 14,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "甲辰"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 26,
            "dayOfWeek": 5,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 15,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "乙巳"
        },
        {
            "publicHoliday": false,
            "today": false,
            "dateOfMonth": 27,
            "dayOfWeek": 6,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 16,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "丙午"
        },
        {
            "publicHoliday": true,
            "today": false,
            "dateOfMonth": 28,
            "dayOfWeek": 0,
            "animalOfYear": "牛",
            "month": 1,
            "year": 2021,
            "lunarDate": 17,
            "lunarMonth": 1,
            "lunarYear": 2021,
            "isLeap": false,
            "chineseYearName": "辛丑",
            "chineseMonthName": "庚寅",
            "chineseDayName": "丁未"
        }
    ],
    "noOfWorkingDay": 18
}
excelExporter.doExport()
.then(()=>{
    console.log("Export Completed.");
})
.catch(error=>{
    console.log("Something Wrong:"+error.stack);
})